### ISSUE TITLE
Loading error after update

### ISSUE THREAD

**Issue by 807502278** [vivax3794/ComfyUI-Sub-Nodes#29]
```
Warn!: Traceback (most recent call last):
  File "D:\AI\ComfyUI-3D\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-Sub-Nodes\__init__.py", line 15, in <module>
    from comfy_execution.graph_utils import GraphBuilder, is_link
ModuleNotFoundError: No module named 'comfy_execution.graph_utils'
```
I went in and looked at it, but I didn't find this file

**Comment by vivax3794** [comment]
What version of comfy are you using? the latest update switched to using some new core comfy features that were added around a week ago

**Comment by 807502278** [comment]
Thank you, it can now be used normally
